kind: Deployment
apiVersion: apps/v1
metadata:
  name: a62
  labels:
    app: a62
    app.kubernetes.io/part-of: a62
spec:
  replicas: 1
  selector:
    matchLabels:
      app: a62
  template:
    metadata:
      labels:
        app: a62
    spec:
      containers:
      - name: a62
        image: ghcr.io/im23b-schneidert/a62:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
kind: Service
apiVersion: v1
metadata:
  name: a62
  labels:
    app: a62
    app.kubernetes.io/part-of: a62
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
  selector:
    app: a62
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: a62
  labels:
    app: a62
    app.kubernetes.io/part-of: a62
spec:
  to:
    kind: Service
    name: a62
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect