kind: Deployment
apiVersion: apps/v1
metadata:
  name: a62
  labels:
    app: a62
    app.kubernetes.io/part-of: a62
spec:
  replicas: 1
  selector:
    matchLabels:
      app: a62
  template:
    metadata:
      labels:
        app: a62
    spec:
      containers:
      - name: a62
        image: ghcr.io/im23b-schneidert/a62:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}