kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: a62
  labels:
    app: a62
    app.kubernetes.io/part-of: a62
spec:
  to:
    kind: Service
    name: a62
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect