kind: Service
apiVersion: v1
metadata:
  name: a62
  labels:
    app: a62
    app.kubernetes.io/part-of: a62
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
  selector:
    app: a62